#ifndef __CRANE_NEW_MODEL_DATA_H__
#define __CRANE_NEW_MODEL_DATA_H__

//this file is generated by tflite2c.py

#include <stdint.h>
extern const unsigned char g_crane_new_model_data[];
extern const unsigned int g_crane_new_model_data_len;
extern const char* g_crane_new_model_classes[];
extern const unsigned int g_crane_new_model_classes_num;

#endif
